### ISSUE TITLE
Update to new ubuntu versions

### ISSUE THREAD

**Issue by phpfs** [deric/puppet-beegfs#20]
Hi @deric,

thank you for this great module.
Can we add the new Ubuntu (& Debian) versions?
```
Ubuntu            Debian  
21.04  hirsute    bullseye/ sid   - 11
20.10  groovy     bullseye/ sid
20.04  focal      bullseye/ sid
```

Thank you :)

**Comment by deric** [comment]
@phpfs Your welcome :slightly_smiling_face:, released as [`v07.0`](https://github.com/deric/puppet-beegfs/releases/tag/v0.7.0)
