### ISSUE TITLE
Testing module version 0.8.0 results in Unknown variable: 'beegfs::mgmtd_host'

### ISSUE THREAD

**Issue by trenta** [deric/puppet-beegfs#35]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: 'beegfs::mgmtd_host'. (file: /etc/puppetlabs/code/environments/env/modules/beegfs/manifests/meta.pp, line: 33, column: 63) on node test-beegfs01.svi.edu.au

**Comment by deric** [comment]
Sorry about that, I made that change a long time ago and forgot to properly test it :( Should be fixed in [v0.8.1](https://github.com/deric/puppet-beegfs/releases/tag/v0.8.1)
